clusterName: local.name
centralEndpoint: "central.acme-labs.internal"

env:
  istio: true  # enable istio support

sensor:
  # Use custom resource overrides for sensor
  resources:
    requests:
      cpu: "1"
      memory: "1Gi"
    limits:
      cpu: "2"
      memory: "4Gi"

admissionControl:
  dynamic:
    disableBypass: true # Disable bypassing of Admission Controller

customize:
  # Apply the important-service=true label for all objects managed by this chart.
  labels:
    important-service: true
  # Set the CLUSTER=important-cluster environment variable for all containers in the
  # collector deployment:
  collector:
    envVars:
      CLUSTER: sysdig-splunk-integration-cluster2
