global:
  kspm:
    deploy: true
ebpf:
    enabled: false
nodeAnalyzer:
  nodeAnalyzer:
    benchmarkRunner:
      deploy: false
    runtimeScanner:
      settings:
        eveEnabled: true
  secure:
    vulnerabilityManagement:
      newEngineOnly: true
